name: MHRegistry
version: 1.0-SNAPSHOT
main: com.domaincord.MHRegistry.MHRegistry
api-version: 1.20
depend: [WorldGuard]
softdepend: [WorldEdit]
commands:
  submitbuild:
    description: Submits a server build to the external platform
    usage: /<command> <buildName> <regionName>
    permission: mhregistry.submit
permissions:
  mhregistry.submit:
    description: Allows submitting builds
    default: op